# Problem 1

In [2]:
import numpy as np

In [2]:
a = np.random.randint(1, 50, (5,4)) # matrix initialisation
print(a)

[[43 46 15 19]
 [49 24  1 23]
 [40 11  1  3]
 [23 39 21 17]
 [27  9 13 12]]


In [3]:
for i in range(4) :    # anti diagonal elements
  print(a[i][3-i])

19
1
11
23


In [4]:
mean = np.mean(a)
print(mean)

21.8


In [7]:
new_a = a[a <= mean]
print(new_a)

[15 19  1 11  1  3 21 17  9 13 12]


In [30]:
def numpy_boundary_traversal(matrix) :  # function
  top = matrix[0, :]
  right = matrix[1:, -1]
  bottom = matrix[-1, -2 ::-1]
  left = matrix[-2:1:-1, 0]

  return np.concatenate([top, right, bottom, left])


res = numpy_boundary_traversal(a)
print(res)


[43 46 15 19 23  3 17 12 13  9 27 23 40]


# Problem 2

In [25]:
b = np.random.rand(20)*10
print(b)
print(b.dtype)
b = b.round(2)
print(b)

[3.89630208 2.27234422 4.24958334 8.2496675  1.7304691  4.43868741
 2.71497067 2.83640026 1.98264197 5.69148722 2.67039726 9.87063512
 3.79450945 2.52564223 8.32998169 6.57642181 8.1048231  7.33200031
 1.99305662 6.63599466]
float64
[3.9  2.27 4.25 8.25 1.73 4.44 2.71 2.84 1.98 5.69 2.67 9.87 3.79 2.53
 8.33 6.58 8.1  7.33 1.99 6.64]


In [26]:
print(b.min())

1.73


In [27]:
print(b.max())

9.87


In [28]:
print(np.median(b))

4.075


In [29]:
b[b < 5] = b[b<5]**2
print(b)

[15.21    5.1529 18.0625  8.25    2.9929 19.7136  7.3441  8.0656  3.9204
  5.69    7.1289  9.87   14.3641  6.4009  8.33    6.58    8.1     7.33
  3.9601  6.64  ]


In [33]:
def numpy_alternate_sort(matrix) :
  sort_arr = np.sort(matrix)
  n = matrix.shape[0]
  res = np.empty(n, dtype= matrix.dtype)
  res[::2] = sort_arr[:(n+1)//2]
  res[1::2] = sort_arr[n-1:(n-1)//2:-1]
  return res

res = numpy_alternate_sort(b)
print(res)

[ 2.9929 19.7136  3.9204 18.0625  3.9601 15.21    5.1529 14.3641  5.69
  9.87    6.4009  8.33    6.58    8.25    6.64    8.1     7.1289  8.0656
  7.33    7.3441]


# Problem 3

In [3]:
import pandas as pd

# creating the data frame from a dict
names = ['Raj', 'Ash', 'Virat', 'Neha', 'Shreya', 'Rahul', 'Bob',
         'Robin', 'Steve', 'Dude']
subjects = ['Math', 'Math', 'Physics', 'English', 'History', 'Physics',
            'Chemistry', 'Physics', 'Chemistry', 'History']

scores = np.random.randint(50, 100, (10,))

dict = {'Name' : names, 'Subject' : subjects,
        'Score' : scores}

df = pd.DataFrame(dict)
df

Name    Subject  Score
0     Raj       Math     64
1     Ash       Math     70
2   Virat    Physics     94
3    Neha    English     98
4  Shreya    History     83
5   Rahul    Physics     86
6     Bob  Chemistry     73
7   Robin    Physics     82
8   Steve  Chemistry     72
9    Dude    History     84

In [5]:
def grade(score) :   # grade function
  if score >= 90 :
    return 'A'
  elif score >= 80 :
    return 'B'
  elif score >= 70 :
    return 'C'
  elif score >= 60 :
    return 'D'
  else :
    return 'F'

In [6]:
df['Grade'] = [grade(score) for score in scores]
df

Name    Subject  Score Grade
0     Raj       Math     64     D
1     Ash       Math     70     C
2   Virat    Physics     94     A
3    Neha    English     98     A
4  Shreya    History     83     B
5   Rahul    Physics     86     B
6     Bob  Chemistry     73     C
7   Robin    Physics     82     B
8   Steve  Chemistry     72     C
9    Dude    History     84     B

In [19]:
df = df.sort_values('Score', ascending=False) # sorting the values
df.reset_index(drop=True, inplace=True)
df

Name    Subject  Score Grade
0    Neha    English     98     A
1   Virat    Physics     94     A
2   Rahul    Physics     86     B
3    Dude    History     84     B
4  Shreya    History     83     B
5   Robin    Physics     82     B
6     Bob  Chemistry     73     C
7   Steve  Chemistry     72     C
8     Ash       Math     70     C
9     Raj       Math     64     D

In [20]:
df.groupby('Subject')['Score'].mean() # average scores for each subject

Subject
Chemistry    72.500000
English      98.000000
History      83.500000
Math         67.000000
Physics      87.333333
Name: Score, dtype: float64

In [21]:
def pandas_filter_pass(dataframe) :   # filter function
  return dataframe[(dataframe['Grade'] == 'A') | (dataframe['Grade'] == 'B')]

In [22]:
new_df = pandas_filter_pass(df)
new_df

Name  Subject  Score Grade
0    Neha  English     98     A
1   Virat  Physics     94     A
2   Rahul  Physics     86     B
3    Dude  History     84     B
4  Shreya  History     83     B
5   Robin  Physics     82     B

# Problem 4

In [23]:
import sklearn
import json

In [24]:
class Review:
  def __init__(self, text, score) :
    self.text = text
    self.score = score

  def sentiment(self) :
    if self.score <= 2 :
      return 'NEGATIVE'
    elif self.score >= 4 :
      return 'POSITIVE'
    else :
      return 'NEUTRAL'

  def goodbad(self) :
    if self.score >= 4 :
      return 'BAD'
    elif self.score <= 2 :
      return 'GOOD'

# found this dataset online (which contains reviews of users on amazon and their ratings)
file_name = '/content/Books_small.json'
reviews = []
with open(file_name) as f:
  for line in f:
    review = json.loads(line)
    reviews.append(Review(review['reviewText'], review['overall']))
len(reviews)

1000

In [29]:
pos_sample = []
neg_sample = []
for review in reviews :
  if review.sentiment() == 'POSITIVE' :
    pos_sample.append(review)
  elif review.sentiment() == 'NEGATIVE' :
    neg_sample.append(review)

In [31]:
# getting the required dataset
from random import shuffle
pos_sample = pos_sample[:50]
neg_sample = neg_sample[:50]
samples = pos_sample + neg_sample
shuffle(samples)
len(samples)

100

In [35]:
df = pd.DataFrame([x.text for x in samples], columns=['text'])
df['sentiment'] = [x.sentiment() for x in samples]
df['goodbad'] = [x.goodbad() for x in samples]
df   # this is the dataset, can be used for both 4th and 5th question

text sentiment goodbad
0   I rely on reviews to purchase a book.  And I w...  NEGATIVE    GOOD
1   Not my type of mystery. Was able to determine ...  NEGATIVE    GOOD
2   Just when it was getting excited when a book h...  NEGATIVE    GOOD
3   Love the book, great story line, keeps you ent...  POSITIVE     BAD
4   This is a prologue to his new book &#34;Innoce...  POSITIVE     BAD
..                                                ...       ...     ...
95  Cambria Hebert is an author that I wait anxiou...  POSITIVE     BAD
96  This would make a excellent movie. Definitely ...  POSITIVE     BAD
97  I really enjoyed this book. It was a well writ...  POSITIVE     BAD
98  If I had know that this was in comic book form...  NEGATIVE    GOOD
99  I have no heart for men who wanna run the stre...  NEGATIVE    GOOD

[100 rows x 3 columns]

In [36]:
# dataframe for 4th question
movie_df = df.drop('goodbad', axis=1)
movie_df

text sentiment
0   I rely on reviews to purchase a book.  And I w...  NEGATIVE
1   Not my type of mystery. Was able to determine ...  NEGATIVE
2   Just when it was getting excited when a book h...  NEGATIVE
3   Love the book, great story line, keeps you ent...  POSITIVE
4   This is a prologue to his new book &#34;Innoce...  POSITIVE
..                                                ...       ...
95  Cambria Hebert is an author that I wait anxiou...  POSITIVE
96  This would make a excellent movie. Definitely ...  POSITIVE
97  I really enjoyed this book. It was a well writ...  POSITIVE
98  If I had know that this was in comic book form...  NEGATIVE
99  I have no heart for men who wanna run the stre...  NEGATIVE

[100 rows x 2 columns]

In [64]:
# feature extraction
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(movie_df, test_size=0.2)
vectorizer = CountVectorizer(max_features=500,lowercase=True ,stop_words='english')

train_x = vectorizer.fit_transform(train_df['text'])
train_y = train_df['sentiment']
test_x = vectorizer.transform(test_df['text'])
test_y = test_df['sentiment']

In [74]:
from sklearn.naive_bayes import MultinomialNB  # model training
classifier = MultinomialNB()
classifier.fit(train_x.toarray(), train_y)
y_pred = classifier.predict(test_x.toarray())
# print(y_pred)

In [72]:
from sklearn.metrics import accuracy_score  # accuracy
print(accuracy_score(test_y, y_pred))

0.65


In [69]:
def predict_review_sentiment(model, vectorizer, review) : # function
  review = vectorizer.transform([review])
  return model.predict(review)

In [71]:
review = movie_df['text'][0]
print(review)
print(predict_review_sentiment(classifier, vectorizer, review))

I rely on reviews to purchase a book.  And I was sorely misled from previous five star reviews.Spoiler alert:I'd like to punch Sophia and throw my reader at wall to hopefully re-arrange the 'story'.  I can identify with Sophia because work comes first.She doesn't seem like a nice person.  Conflict is needed for drama but she must be the most gorgeous person ever.  She's catty and judgmental.  I don't know where to start.I keep hoping the story gets better but she just gets crazy gf syndrome as I turn the page.  And it's not good gf drama, nothing like Tarryn Fisher's 'The Opportunist' nor are there FSOG aspects.  Just some good looking rich guy.
['NEGATIVE']


# Problem 5

In [75]:
# dataframe for the 5th question
text_df = df.drop('sentiment', axis = 1)
text_df

text goodbad
0   I rely on reviews to purchase a book.  And I w...    GOOD
1   Not my type of mystery. Was able to determine ...    GOOD
2   Just when it was getting excited when a book h...    GOOD
3   Love the book, great story line, keeps you ent...     BAD
4   This is a prologue to his new book &#34;Innoce...     BAD
..                                                ...     ...
95  Cambria Hebert is an author that I wait anxiou...     BAD
96  This would make a excellent movie. Definitely ...     BAD
97  I really enjoyed this book. It was a well writ...     BAD
98  If I had know that this was in comic book form...    GOOD
99  I have no heart for men who wanna run the stre...    GOOD

[100 rows x 2 columns]

In [78]:
# feature extraction
from sklearn.feature_extraction.text import TfidfVectorizer

train, test = train_test_split(text_df, test_size =0.25)
vectorizer = TfidfVectorizer(max_features=300,lowercase=True ,stop_words='english')

train_x = vectorizer.fit_transform(train['text'])
train_y = train['goodbad']
test_x = vectorizer.transform(test['text'])
test_y = test['goodbad']

In [79]:
# model training and prediction
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(train_x.toarray(), train_y)
y_pred = logistic.predict(test_x.toarray())

In [80]:
# evaluation
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
print("Accuracy : ", accuracy_score(test_y, y_pred))
print("Recall", recall_score(test_y, y_pred, pos_label='GOOD'))
print("Precision", precision_score(test_y, y_pred, pos_label='GOOD'))
print("F1 Score", f1_score(test_y, y_pred, pos_label='GOOD'))

Accuracy :  0.68
Recall 0.6363636363636364
Precision 0.6363636363636364
F1 Score 0.6363636363636364


In [86]:
# function
def text_preprocess_vectorize(texts, vectorizer) :
  return vectorizer.transform(texts)

In [84]:
texts = list(test_df['text'][0:10])
print(texts)
len(texts)

['There is nothing to this book.  Just a VERY basic overview of the topic.  Few examples.  The book is not worth the money.  The actual content of the book would equal about a third of a page typed on a page.  I could probably write this myself if I were to get on Google and copy and paste a few things.', "The book talks a lot about getting ready for projection. A certain mindset. It talks about being fearful of sleep paralysis and how meditation plus lucid dreaming helps to archive astral travel.The reason I'm giving it a 1 star is because the most critical element, according to the book, to actually being able to project, requires  &#34;sleep paralysis&#34;, and the book spends almost no time at all on how to achieve it.Here's a section on sleep paralysis:&#34;Is there a way to activate or consciously create sleep paralysis? I haven&#8217;t found a way to consciously induce it, however, there are several conditions which almost always lead to sleep paralysis. One is being on your bac

10

In [89]:
feature_matrix = text_preprocess_vectorize(texts, vectorizer)
print(feature_matrix.shape)

(10, 300)
